#! /bin/sh

pidof sxhkd                  || sxhkd &
pidof feh                    || feh --bg-scale ~/Pictures/Backgrounds/gentoo_background &
pidof setxkbmap              || setxkbmap us,ara -option grp:lalt_lshift_toggle &
pidof polybar                || polybar top &
pidof picom                  || picom --experimental-backends &
pidof buckle                 || buckle &
pidof dunst                  || dunst &

# Border colors
bspc config normal_border_color   "#0A0E14"
bspc config focused_border_color  "#88C0D0"
bspc config urgent_border_color   "#e6b450"
bspc config presel_border_color   "#B3B1AD"

bspc monitor -d I II III IV V VI VII

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.67
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true

bspc rule -a Zathura state=tiled
